### ISSUE TITLE
Git clone fails

### ISSUE THREAD

**Issue by baali** [getsenic/senic-os-linux#2]
Seems there is issue with the default branch of the repository and when cloned it fails with the error:

`warning: remote HEAD refers to nonexistent ref, unable to checkout.`

This [link](https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/) have details on how to fix it.

**Comment by TheMeaningfulEngineer** [comment]
Is this still an actual issue?

**Comment by baali** [comment]
When I cloned last time it worked.
